### ISSUE TITLE
[Feature] Create a Dialogbox to Browse Image

### ISSUE THREAD

**Issue by pooranjoyb** [Sampreet-cell/Cartoonifier#1]
### Description

The user needs to add file location manually in the following code.

https://github.com/Sampreet-cell/Cartoonifier/blob/20dc0b61c922bb6256073af4d24b9e5707fc6653/cartoon.py#L25

### Feature
- [x] I would create a separate Dialogbox that will take input by browsing file location
- [x] It will run on execution of the .py file.

Assign me this issue. @Sampreet-cell

**Comment by Sampreet-cell** [comment]
Great idea, go for it👍👍👍
